// Default Theme Colors
export const baseColors = {
  primary: `#fff`,
  secondary: `#121212`,
  background: `$primary`,
  foreground: `$secondary`,
  heading: `$secondary`,
  subheading: `#afafaf`,
  body: `#000`,
  divider: `#e4e4e4`,
  'search-input': `$contrast`,
  'icon-stroke': `$secondary`,
  'icon-fill': `$secondary`,
  'accent-background': `$secondary`,
  'accent-foreground': `$primary`,
  contrast: `#f8f8f8`,
  'x-contrast': `#f4f4f4`,
  'xx-contrast': `#e6e6e6`,
  'xxx-contrast': `#bbb`,
  'xxxx-contrast': `#707070`,
  'menu-background': `rgba(255, 255, 255, 0.85)`,
  'footer-background': `$contrast`,
};

// Dark theme colors
export const darkColors = {
  primary: `#000`,
  secondary: `#fff`,
  heading: `$secondary`,
  body: `$secondary`,
  background: `$primary`,
  foreground: `$secondary`,
  divider: `#333`,
  'search-input': `$secondary`,
  'icon-stroke': `$secondary`,
  'icon-fill': `$secondary`,
  'accent-background': `$secondary`,
  'accent-foreground': `$primary`,
  contrast: `#121212`,
  'x-contrast': `#4c4c4c`,
  'xx-contrast': `#797979`,
  'xxx-contrast': `#a2a2a2`,
  'xxxx-contrast': `#cacaca`,
  'menu-background': `rgba(0, 0, 0, 0.95)`,
  'footer-background': `#1E1E1E`,
};
